// flow-typed signature: 7391f907f40245411ffb07f99b7986f2
// flow-typed version: <<STUB>>/react-emojione2_v^2.2.18/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-emojione2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-emojione2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-emojione2/lib/data/ascii-to-unicode' {
  declare module.exports: any;
}

declare module 'react-emojione2/lib/data/emoji-data' {
  declare module.exports: any;
}

declare module 'react-emojione2/lib/react-emojione' {
  declare module.exports: any;
}

declare module 'react-emojione2/lib/renderers/emoji-renderer' {
  declare module.exports: any;
}

declare module 'react-emojione2/lib/renderers/renderer-factory' {
  declare module.exports: any;
}

declare module 'react-emojione2/lib/renderers/unicode-renderer' {
  declare module.exports: any;
}

declare module 'react-emojione2/lib/styles/emojione-sprite-positions' {
  declare module.exports: any;
}

declare module 'react-emojione2/lib/styles/emojione-sprite' {
  declare module.exports: any;
}

declare module 'react-emojione2/lib/utils/emoji-format-conversion' {
  declare module.exports: any;
}

declare module 'react-emojione2/scripts/create-emoji-data' {
  declare module.exports: any;
}

declare module 'react-emojione2/scripts/create-styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-emojione2/lib/data/ascii-to-unicode.js' {
  declare module.exports: $Exports<'react-emojione2/lib/data/ascii-to-unicode'>;
}
declare module 'react-emojione2/lib/data/emoji-data.js' {
  declare module.exports: $Exports<'react-emojione2/lib/data/emoji-data'>;
}
declare module 'react-emojione2/lib/react-emojione.js' {
  declare module.exports: $Exports<'react-emojione2/lib/react-emojione'>;
}
declare module 'react-emojione2/lib/renderers/emoji-renderer.js' {
  declare module.exports: $Exports<'react-emojione2/lib/renderers/emoji-renderer'>;
}
declare module 'react-emojione2/lib/renderers/renderer-factory.js' {
  declare module.exports: $Exports<'react-emojione2/lib/renderers/renderer-factory'>;
}
declare module 'react-emojione2/lib/renderers/unicode-renderer.js' {
  declare module.exports: $Exports<'react-emojione2/lib/renderers/unicode-renderer'>;
}
declare module 'react-emojione2/lib/styles/emojione-sprite-positions.js' {
  declare module.exports: $Exports<'react-emojione2/lib/styles/emojione-sprite-positions'>;
}
declare module 'react-emojione2/lib/styles/emojione-sprite.js' {
  declare module.exports: $Exports<'react-emojione2/lib/styles/emojione-sprite'>;
}
declare module 'react-emojione2/lib/utils/emoji-format-conversion.js' {
  declare module.exports: $Exports<'react-emojione2/lib/utils/emoji-format-conversion'>;
}
declare module 'react-emojione2/scripts/create-emoji-data.js' {
  declare module.exports: $Exports<'react-emojione2/scripts/create-emoji-data'>;
}
declare module 'react-emojione2/scripts/create-styles.js' {
  declare module.exports: $Exports<'react-emojione2/scripts/create-styles'>;
}
