// flow-typed signature: 465a9435cb1019c4ae1f0b90f7d7892b
// flow-typed version: <<STUB>>/superagent-jsonp_v^0.1.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-jsonp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-jsonp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superagent-jsonp/dist/superagent-jsonp' {
  declare module.exports: any;
}

declare module 'superagent-jsonp/gulpfile' {
  declare module.exports: any;
}

declare module 'superagent-jsonp/src/superagent-jsonp' {
  declare module.exports: any;
}

declare module 'superagent-jsonp/test/superagent_jsonp_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superagent-jsonp/dist/superagent-jsonp.js' {
  declare module.exports: $Exports<'superagent-jsonp/dist/superagent-jsonp'>;
}
declare module 'superagent-jsonp/gulpfile.js' {
  declare module.exports: $Exports<'superagent-jsonp/gulpfile'>;
}
declare module 'superagent-jsonp/src/superagent-jsonp.js' {
  declare module.exports: $Exports<'superagent-jsonp/src/superagent-jsonp'>;
}
declare module 'superagent-jsonp/test/superagent_jsonp_spec.js' {
  declare module.exports: $Exports<'superagent-jsonp/test/superagent_jsonp_spec'>;
}
