version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: mkdir -p netlify
      - run: cp -a public/* netlify/
      - run: mv -f netlify/index.production.html netlify/index.html
  test:
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm run test
  deploy:
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - deploy: ./node_modules/.bin/netlify deploy -p netlify -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
