version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:latest
    working_directory: ~/workflows
    steps:
      - checkout
      - restore_cache:
          key: modules-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - run: mkdir -p netlify
      - run: cp -a public/* netlify/
      - run: mv -f netlify/index.production.html netlify/index.html
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/workflows
      - save_cache:
          key: modules-{{ checksum "package.json" }}
          paths:
            - ~/workflows/node_modules
  test:
    docker: 
      - image: circleci/node:latest
    working_directory: ~/workflows
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: modules-{{ checksum "package.json" }}
      - run: npm run test
  deploy:
    docker: 
      - image: circleci/node:latest
    steps:
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - deploy: 
          name: Deploy to netlify
          command: ./node_modules/.bin/netlify deploy -p netlify -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
